services:
    mrm_entity_validation.entity_validation_listener:
        class: MrM\EntityValidationBundle\Extensions\EntityValidationListener        
        calls:
          - [ setContainer,  ["@service_container"] ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }